const MIME_ARCHIVE = [
  "application/zip",
  "application/x-zip",
  "application/x-zip-compressed",
  "application/x-7z-compressed",
  "application/x-installshield",
  "application/lzip",
  "application/x-lzip",
  "application/x-xz",
  "application/x-rar",
  "application/x-rar-compressed",
  "application/gzip",
  "application/x-gzip",
  "application/x-gunzip",
  "application/gzipped",
  "application/gzip-compressed",
  "application/x-gzip-compressed",
  "gzip/document",
  "application/x-bzip2",
  "application/x-tar",
  "application/x-xar",
  "application/vnd.ms-cab-compressed",
  "application/x-installshield",
  "application/x-chrome-extension",
  "application/zstd",
  "application/x-cpio",
];
const MIME_AUDIO = [
  "application/ogg",
  "audio/aac",
  "audio/ogg",
  "audio/3gpp",
  "audio/3gpp2",
  "audio/mpeg",
  "audio/x-mpeg",
  "audio/mp3",
  "audio/flac",
  "audio/midi",
  "audio/mid",
  "audio/sp-midi",
  "audio/x-mid",
  "audio/x-midi",
  "audio/ape",
  "audio/musepack",
  "audio/amr",
  "audio/amr-nb",
  "audio/wav",
  "audio/x-wav",
  "audio/vnd.wave",
  "audio/wave",
  "audio/aiff",
  "audio/x-aiff",
  "audio/basic",
  "audio/x-unknown",
  "audio/mp4",
  "audio/x-m4a",
  "audio/x-mp4a",
  "audio/x-m4a",
  "application/ogg",
  "application/x-ogg",
  "application/vnd.apple.mpegurl",
  "audio/mpegurl",
  "audio/qcelp",
];
const MIME_BINARY = [
  "application/octet-stream",
  "application/jar",
  "application/vnd.microsoft.portable-executable",
  "application/x-executable",
  "application/x-elf",
  "application/x-object",
  "application/x-ms-installer",
  "application/x-windows-installer",
  "application/x-msi",
  "application/x-shockwave-flash",
  "application/vnd.nintendo.snes.rom",
  "application/vnd.debian.binary-package",
  "application/x-rpm",
  "application/wasm",
  "application/x-ms-shortcut",
  "application/x-sharedlib",
  "application/x-mach-binary",
  "application/x-coredump",
];
const MIME_DOCUMENT = [
  "text/rtf",
  "application/pdf",
  "application/x-pdf",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/epub+zip",
  "application/vnd.oasis.opendocument.text",
  "application/x-vnd.oasis.opendocument.text",
  "application/vnd.oasis.opendocument.text-template",
  "application/x-vnd.oasis.opendocument.text-template",
  "application/vnd.oasis.opendocument.spreadsheet",
  "application/x-vnd.oasis.opendocument.spreadsheet",
  "application/vnd.oasis.opendocument.spreadsheet-template",
  "application/x-vnd.oasis.opendocument.spreadsheet-template",
  "application/vnd.oasis.opendocument.presentation",
  "application/x-vnd.oasis.opendocument.presentation",
  "application/vnd.oasis.opendocument.presentation-template",
  "application/x-vnd.oasis.opendocument.presentation-template",
  "application/vnd.oasis.opendocument.graphics",
  "application/x-vnd.oasis.opendocument.graphics",
  "application/vnd.oasis.opendocument.graphics-template",
  "application/x-vnd.oasis.opendocument.graphics-template",
  "application/vnd.oasis.opendocument.formula",
  "application/x-vnd.oasis.opendocument.formula",
  "application/vnd.oasis.opendocument.chart",
  "application/x-vnd.oasis.opendocument.chart",
  "application/vnd.sun.xml.calc",
  "application/vnd.ms-excel",
  "application/msexcel",
  "application/vnd.ms-publisher",
  "application/vnd.ms-powerpoint",
  "application/mspowerpoint",
  "application/msword",
  "application/vnd.ms-word",
  "application/x-msaccess",
  "application/vnd.ms-outlook",
  "font/ttf",
  "font/sfnt",
  "application/x-font-ttf",
  "application/font-sfnt",
  "font/woff",
  "font/woff2",
  "font/otf",
  "font/collection",
  "application/vnd.sqlite3",
  "application/x-sqlite3",
  "application/x-mobipocket-ebook",
  "application/x-ms-reader",
  "application/vnd.fdf",
  "application/vnd.adobe.xfdf",
  "application/x-ole-storage",
  "application/pkcs7-signature",
  "application/x-dbf",
  "application/vnd.ms-fontobject",
  "application/vnd.shx",
  "application/vnd.shp",
  "application/tzif",
  "application/warc",
];
const MIME_GRAPHIC = [
  "image/vnd.adobe.photoshop",
  "image/x-psd",
  "application/photoshop",
  "application/fits",
  "image/vnd.dwg",
  "image/x-dwg",
  "application/acad",
  "application/x-acad",
  "application/autocad_dwg",
  "application/dwg",
  "application/x-dwg",
  "application/x-autocad",
  "drawing/dwg",
  "image/x-gimp-pat",
  "image/x-gimp-gbr",
  "image/x-xcf",
  "model/gltf-binary",
  "image/vnd.djvu",
  "application/postscript",
  "application/dicom",
  "image/vnd.radiance",
  "application/marc",
  "image/x-xpixmap",
];
const MIME_IMAGE = [
  "image/gif",
  "image/png",
  "image/jpeg",
  "image/svg+xml",
  "image/vnd.mozilla.apng",
  "image/jxl",
  "image/jp2",
  "image/jpx",
  "image/jpm",
  "image/jxs",
  "image/webp",
  "image/tiff",
  "image/bmp",
  "image/x-bmp",
  "image/x-ms-bmp",
  "image/x-icon",
  "image/x-icns",
  "image/heic",
  "image/heic-sequence",
  "image/heif",
  "image/heif-sequence",
  "image/bpg",
  "image/avif",
  "image/jxr",
  "image/vnd.ms-photo",
];
const MIME_TEXT = [
  "text/plain",
  "application/json",
  "text/csv",
  "application/javascript",
  "application/x-javascript",
  "text/javascript",
  "text/x-php",
  "text/x-perl",
  "text/x-lua",
  "text/rss",
  "application/rss+xml",
  "text/xml",
  "text/html",
  "text/x-python",
  "text/x-script.python",
  "application/x-python",
  "application/x-subrip",
  "application/x-srt",
  "text/x-srt",
  "text/tab-separated-values",
  "text/vcard",
  "text/calendar",
  "application/x-java-applet",
  "application/geo+json",
  "application/x-ndjson",
  "text/vtt",
  "text/x-tcl",
  "application/x-tcl",
  "application/atom+xml",
  "application/x-bittorrent",
  "model/x3d+xml",
  "application/x-archive",
  "application/x-unix-archive",
  "application/owl+xml",
  "application/gml+xml",
  "application/gpx+xml",
  "application/vnd.garmin.tcx+xml",
  "application/vnd.google-earth.kml+xml",
  "application/x-xliff+xml",
  "model/vnd.collada+xml",
  "application/vnd.ms-package.3dmanufacturing-3dmodel+xml",
  "application/x-amf",
];
const MIME_VIDEO = [
  "audio/mp4",
  "audio/x-m4a",
  "audio/x-mp4a",
  "video/x-matroska",
  "video/ogg",
  "video/mpeg",
  "video/mp4",
  "video/webm",
  "audio/webm",
  "video/quicktime",
  "video/3gpp",
  "video/3gp",
  "video/3gpp2",
  "video/3g2",
  "video/x-msvideo",
  "video/avi",
  "video/msvideo",
  "video/x-flv",
  "video/x-ms-asf",
  "video/asf",
  "video/x-ms-wmv",
  "video/x-m4v",
  "video/jpm",
  "application/vnd.rn-realmedia-vbr",
];

export enum MimeType {
  Archive,
  Audio,
  Binary,
  Document,
  Graphic,
  Image,
  Text,
  Video,
}

const stripMime = (mime: string) => mime.split(";")[0];

export const mime = (mime: string) => {
  mime = stripMime(mime);

  if (isArchive(mime)) return MimeType.Archive;
  if (isAudio(mime)) return MimeType.Audio;
  if (isDocument(mime)) return MimeType.Document;
  if (isGraphic(mime)) return MimeType.Graphic;
  if (isImage(mime)) return MimeType.Image;
  if (isText(mime)) return MimeType.Text;
  if (isVideo(mime)) return MimeType.Video;

  return MimeType.Binary;
};

export const isArchive = (mime: string) =>
  MIME_ARCHIVE.includes(stripMime(mime));
export const isAudio = (mime: string) => MIME_AUDIO.includes(stripMime(mime));
export const isBinary = (mime: string) => MIME_BINARY.includes(stripMime(mime));
export const isDocument = (mime: string) =>
  MIME_DOCUMENT.includes(stripMime(mime));
export const isGraphic = (mime: string) =>
  MIME_GRAPHIC.includes(stripMime(mime));
export const isImage = (mime: string) => MIME_IMAGE.includes(stripMime(mime));
export const isText = (mime: string) => MIME_TEXT.includes(stripMime(mime));
export const isVideo = (mime: string) => MIME_VIDEO.includes(stripMime(mime));
