name: Push to Server

on:
  push:
    branches: ['main']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./clients
    strategy:
      matrix:
        node-version: [18]
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    
    - uses: pnpm/action-setup@v2
      with:
        version: 7

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: client/pnpm-lock.yaml
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Build app
      run: pnpm build
    
    - name: Copy dist files via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "client/dist/*"
        target: ${{ secrets.CLIENT_TARGET }}